/* eslint-disable global-require */

const images = {
  801: require('../images/thunder.jpg'),
  201: require('../images/thunder.jpg'),
  202: require('../images/thunder.jpg'),
  230: require('../images/thunder.jpg'),
  231: require('../images/thunder.jpg'),
  232: require('../images/thunder.jpg'),
  233: require('../images/thunder.jpg'),
  300: require('../images/Drizzle.jpg'),
  301: require('../images/Drizzle.jpg'),
  302: require('../images/Drizzle.jpg'),
  500: require('../images/Moderaterain.jpg'),
  501: require('../images/Moderaterain.jpg'),
  502: require('../images/Moderaterain.jpg'),
  511: require('../images/Showerrain.jpg'),
  520: require('../images/Showerrain.jpg'),
  521: require('../images/Showerrain.jpg'),
  522: require('../images/Showerrain.jpg'),
  600: require('../images/Snow.jpg'),
  602: require('../images/Snow.jpg'),
  610: require('../images/Snow.jpg'),
  611: require('../images/Sleet.jpg'),
  612: require('../images/Sleet.jpg'),
  621: require('../images/Snowshower.jpg'),
  622: require('../images/Snowshower.jpg'),
  623: require('../images/Snowshower.jpg'),
  700: require('../images/Mist.jpg'),
  711: require('../images/Mist.jpg'),
  721: require('../images/Mist.jpg'),
  731: require('../images/Mist.jpg'),
  741: require('../images/Fog.jpg'),
  751: require('../images/Fog.jpg'),
  800: require('../images/sky.jpg'),
  801: require('../images/sky.jpg'),
  802: require('../images/sky.jpg'),
  803: require('../images/Brokenclouds.jpg'),
  804: require('../images/Brokenclouds.jpg'),
};

export default weather => images[weather];
